# !/bin/env/python

import wx
import sys
import os.path

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))


class CountryCodes(wx.Dialog):
    def __init__(self, *args, **kwds):
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)

        self.listBox = wx.ListBox(self, wx.ID_ANY, choices=self.populateView())

        self.__set_properties()
        self.__do_layout()

    def __set_properties(self):
        self.SetSize((350, 350))
        self.listBox.SetMinSize((300, 300))

    def __do_layout(self):
        groupBox = wx.StaticBox(self, label="Country Codes")
        groupBoxSizer = wx.StaticBoxSizer(groupBox, wx.VERTICAL)

        groupBoxSizer.Add(self.listBox, 1, wx.EXPAND, 5)

        mainSizer = wx.BoxSizer(wx.VERTICAL)
        mainSizer.Add(groupBoxSizer, 1, wx.ALL | wx.EXPAND, 5)

        self.SetSizer(mainSizer)
        self.CentreOnParent()
        self.Layout()

    def populateView(self):
        countryCodes = []
        countryCodes.append("AD   Andorra")
        countryCodes.append("AE   United Arab Emirates")
        countryCodes.append("AF   Afghanistan")
        countryCodes.append("AG   Antigua and Barbuda")
        countryCodes.append("AI   Anguilla")
        countryCodes.append("AL   Albania")
        countryCodes.append("AM   Armenia")
        countryCodes.append("AN   Netherlands Antilles")
        countryCodes.append("AO   Angola")
        countryCodes.append("AQ   Antarctica")
        countryCodes.append("AR   Argentina")
        countryCodes.append("AS   American Samoa")
        countryCodes.append("AT   Austria")
        countryCodes.append("AU   Australia")
        countryCodes.append("AW   Aruba")
        countryCodes.append("AZ   Azerbaijan")
        countryCodes.append("BA   Bosnia and Herzegovina")
        countryCodes.append("BB   Barbados")
        countryCodes.append("BD   Bangladesh")
        countryCodes.append("BE   Belgium")
        countryCodes.append("BF   Burkina Faso")
        countryCodes.append("BG   Bulgaria")
        countryCodes.append("BH   Bahrain")
        countryCodes.append("BI   Burundi")
        countryCodes.append("BJ   Benin")
        countryCodes.append("BM   Bermuda")
        countryCodes.append("BN   Brunei Darussalam")
        countryCodes.append("BO   Bolivia")
        countryCodes.append("BR   Brazil")
        countryCodes.append("BS   Bahamas")
        countryCodes.append("BT   Bhutan")
        countryCodes.append("BV   Bouvet Island")
        countryCodes.append("BW   Botswana")
        countryCodes.append("BY   Belarus")
        countryCodes.append("BZ   Belize")
        countryCodes.append("CA   Canada")
        countryCodes.append("CC   Cocos (Keeling) Islands")
        countryCodes.append("CF   Central African Republic")
        countryCodes.append("CG   Congo")
        countryCodes.append("CH   Switzerland")
        countryCodes.append("CI   Cote D'Ivoire (Ivory Coast)")
        countryCodes.append("CK   Cook Islands")
        countryCodes.append("CL   Chile")
        countryCodes.append("CM   Cameroon")
        countryCodes.append("CN   China")
        countryCodes.append("CO   Colombia")
        countryCodes.append("CR   Costa Rica")
        countryCodes.append("CS   Czechoslovakia (former)")
        countryCodes.append("CU   Cuba")
        countryCodes.append("CV   Cape Verde")
        countryCodes.append("CX   Christmas Island")
        countryCodes.append("CY   Cyprus")
        countryCodes.append("CZ   Czech Republic")
        countryCodes.append("DE   Germany")
        countryCodes.append("DJ   Djibouti")
        countryCodes.append("DK   Denmark")
        countryCodes.append("DM   Dominica")
        countryCodes.append("DO   Dominican Republic")
        countryCodes.append("DZ   Algeria")
        countryCodes.append("EC   Ecuador")
        countryCodes.append("EE   Estonia")
        countryCodes.append("EG   Egypt")
        countryCodes.append("EH   Western Sahara")
        countryCodes.append("ER   Eritrea")
        countryCodes.append("ES   Spain")
        countryCodes.append("ET   Ethiopia")
        countryCodes.append("FI   Finland")
        countryCodes.append("FJ   Fiji")
        countryCodes.append("FK   Falkland Islands (Malvinas)")
        countryCodes.append("FM   Micronesia")
        countryCodes.append("FO   Faroe Islands")
        countryCodes.append("FR   France")
        countryCodes.append("FX   France, Metropolitan")
        countryCodes.append("GA   Gabon")
        countryCodes.append("GB   Great Britain (UK)")
        countryCodes.append("GD   Grenada")
        countryCodes.append("GE   Georgia")
        countryCodes.append("GF   French Guiana")
        countryCodes.append("GH   Ghana")
        countryCodes.append("GI   Gibraltar")
        countryCodes.append("GL   Greenland")
        countryCodes.append("GM   Gambia")
        countryCodes.append("GN   Guinea")
        countryCodes.append("GP   Guadeloupe")
        countryCodes.append("GQ   Equatorial Guinea")
        countryCodes.append("GR   Greece")
        countryCodes.append("GS   S. Georgia and S. Sandwich Isls.")
        countryCodes.append("GT   Guatemala")
        countryCodes.append("GU   Guam")
        countryCodes.append("GW   Guinea-Bissau")
        countryCodes.append("GY   Guyana")
        countryCodes.append("HK   Hong Kong")
        countryCodes.append("HM   Heard and McDonald Islands")
        countryCodes.append("HN   Honduras")
        countryCodes.append("HR   Croatia (Hrvatska)")
        countryCodes.append("HT   Haiti")
        countryCodes.append("HU   Hungary")
        countryCodes.append("ID   Indonesia")
        countryCodes.append("IE   Ireland")
        countryCodes.append("IL   Israel")
        countryCodes.append("IN   India")
        countryCodes.append("IO   British Indian Ocean Territory")
        countryCodes.append("IQ   Iraq")
        countryCodes.append("IR   Iran")
        countryCodes.append("IS   Iceland")
        countryCodes.append("IT   Italy")
        countryCodes.append("JM   Jamaica")
        countryCodes.append("JO   Jordan")
        countryCodes.append("JP   Japan")
        countryCodes.append("KE   Kenya")
        countryCodes.append("KG   Kyrgyzstan")
        countryCodes.append("KH   Cambodia")
        countryCodes.append("KI   Kiribati")
        countryCodes.append("KM   Comoros")
        countryCodes.append("KN   Saint Kitts and Nevis")
        countryCodes.append("KP   Korea (North)")
        countryCodes.append("KR   Korea (South)")
        countryCodes.append("KW   Kuwait")
        countryCodes.append("KY   Cayman Islands")
        countryCodes.append("KZ   Kazakhstan")
        countryCodes.append("LA   Laos")
        countryCodes.append("LB   Lebanon")
        countryCodes.append("LC   Saint Lucia")
        countryCodes.append("LI   Liechtenstein")
        countryCodes.append("LK   Sri Lanka")
        countryCodes.append("LR   Liberia")
        countryCodes.append("LS   Lesotho")
        countryCodes.append("LT   Lithuania")
        countryCodes.append("LU   Luxembourg")
        countryCodes.append("LV   Latvia")
        countryCodes.append("LY   Libya")
        countryCodes.append("MA   Morocco")
        countryCodes.append("MC   Monaco")
        countryCodes.append("MD   Moldova")
        countryCodes.append("MG   Madagascar")
        countryCodes.append("MH   Marshall Islands")
        countryCodes.append("MK   Macedonia")
        countryCodes.append("ML   Mali")
        countryCodes.append("MM   Myanmar")
        countryCodes.append("MN   Mongolia")
        countryCodes.append("MO   Macau")
        countryCodes.append("MP   Northern Mariana Islands")
        countryCodes.append("MQ   Martinique")
        countryCodes.append("MR   Mauritania")
        countryCodes.append("MS   Montserrat")
        countryCodes.append("MT   Malta")
        countryCodes.append("MU   Mauritius")
        countryCodes.append("MV   Maldives")
        countryCodes.append("MW   Malawi")
        countryCodes.append("MX   Mexico")
        countryCodes.append("MY   Malaysia")
        countryCodes.append("MZ   Mozambique")
        countryCodes.append("NA   Namibia")
        countryCodes.append("NC   New Caledonia")
        countryCodes.append("NE   Niger")
        countryCodes.append("NF   Norfolk Island")
        countryCodes.append("NG   Nigeria")
        countryCodes.append("NI   Nicaragua")
        countryCodes.append("NL   Netherlands")
        countryCodes.append("NO   Norway")
        countryCodes.append("NP   Nepal")
        countryCodes.append("NR   Nauru")
        countryCodes.append("NT   Neutral Zone")
        countryCodes.append("NU   Niue")
        countryCodes.append("NZ   New Zealand (Aotearoa)")
        countryCodes.append("OM   Oman")
        countryCodes.append("PA   Panama")
        countryCodes.append("PE   Peru")
        countryCodes.append("PF   French Polynesia")
        countryCodes.append("PG   Papua New Guinea")
        countryCodes.append("PH   Philippines")
        countryCodes.append("PK   Pakistan")
        countryCodes.append("PL   Poland")
        countryCodes.append("PM   St. Pierre and Miquelon")
        countryCodes.append("PN   Pitcairn")
        countryCodes.append("PR   Puerto Rico")
        countryCodes.append("PT   Portugal")
        countryCodes.append("PW   Palau")
        countryCodes.append("PY   Paraguay")
        countryCodes.append("QA   Qatar")
        countryCodes.append("RE   Reunion")
        countryCodes.append("RO   Romania")
        countryCodes.append("RU   Russian Federation")
        countryCodes.append("RW   Rwanda")
        countryCodes.append("SA   Saudi Arabia")
        countryCodes.append("Sb   Solomon Islands")
        countryCodes.append("SC   Seychelles")
        countryCodes.append("SD   Sudan")
        countryCodes.append("SE   Sweden")
        countryCodes.append("SG   Singapore")
        countryCodes.append("SH   St. Helena")
        countryCodes.append("SI   Slovenia")
        countryCodes.append("SJ   Svalbard and Jan Mayen Islands")
        countryCodes.append("SK   Slovak Republic")
        countryCodes.append("SL   Sierra Leone")
        countryCodes.append("SM   San Marino")
        countryCodes.append("SN   Senegal")
        countryCodes.append("SO   Somalia")
        countryCodes.append("SR   Suriname")
        countryCodes.append("ST   Sao Tome and Principe")
        countryCodes.append("SU   USSR (former)")
        countryCodes.append("SV   El Salvador")
        countryCodes.append("SY   Syria")
        countryCodes.append("SZ   Swaziland")
        countryCodes.append("TC   Turks and Caicos Islands")
        countryCodes.append("TD   Chad")
        countryCodes.append("TF   French Southern Territories")
        countryCodes.append("TG   Togo")
        countryCodes.append("TH   Thailand")
        countryCodes.append("TJ   Tajikistan")
        countryCodes.append("TK   Tokelau")
        countryCodes.append("TM   Turkmenistan")
        countryCodes.append("TN   Tunisia")
        countryCodes.append("TO   Tonga")
        countryCodes.append("TP   East Timor")
        countryCodes.append("TR   Turkey")
        countryCodes.append("TT   Trinidad and Tobago")
        countryCodes.append("TV   Tuvalu")
        countryCodes.append("TW   Taiwan")
        countryCodes.append("TZ   Tanzania")
        countryCodes.append("UA   Ukraine")
        countryCodes.append("UG   Uganda")
        countryCodes.append("UK   United Kingdom")
        countryCodes.append("UM   US Minor Outlying Islands")
        countryCodes.append("US   United States")
        countryCodes.append("UY   Uruguay")
        countryCodes.append("UZ   Uzbekistan")
        countryCodes.append("VA   Vatican City State (Holy See)")
        countryCodes.append("VC   Saint Vincent and the Grenadines")
        countryCodes.append("VE   Venezuela")
        countryCodes.append("VG   Virgin Islands (British)")
        countryCodes.append("VI   Virgin Islands (U.S.)")
        countryCodes.append("VN   Viet Nam")
        countryCodes.append("VU   Vanuatu")
        countryCodes.append("WF   Wallis and Futuna Islands")
        countryCodes.append("WS   Samoa")
        countryCodes.append("YE   Yemen")
        countryCodes.append("YT   Mayotte")
        countryCodes.append("YU   Yugoslavia")
        countryCodes.append("ZA   South Africa")
        countryCodes.append("ZM   Zambia")
        countryCodes.append("ZR   Zaire")
        countryCodes.append("ZW   Zimbabwe")
        countryCodes.append("COM   US Commercial")
        countryCodes.append("EDU   US Educational")
        countryCodes.append("GOV   US Government")
        countryCodes.append("INT   International")
        countryCodes.append("MIL   US Military")
        countryCodes.append("NET   Network")
        countryCodes.append("ORG   Non-Profit Organization")
        countryCodes.append("ARPA   Old style Arpanet")
        countryCodes.append("NATO   Nato field")

        return countryCodes